# Generated by Django 4.1.13 on 2024-06-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='Holder',
            field=models.CharField(default='mabdullah.elahi', max_length=200),
        ),
    ]
