# Generated by Django 4.1.13 on 2024-06-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_sales_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Assignment',
            field=models.CharField(default='Website', max_length=200),
        ),
        migrations.AlterField(
            model_name='sales',
            name='ContactNumber',
            field=models.BigIntegerField(default='0000000000'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Date',
            field=models.DateField(default='2024-04-12'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='DateComplete',
            field=models.DateField(default='2024-04-12'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Location',
            field=models.CharField(default='Karachi', max_length=200),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Socials',
            field=models.JSONField(default='empty'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Status',
            field=models.BooleanField(default='off'),
        ),
    ]
