# Generated by Django 4.1.13 on 2024-06-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_sales_accountnumber_alter_sales_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sales',
            table='db_sales',
        ),
    ]
